// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManager.Api.Context;

namespace RecipeManager.Api.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20181107092618_InitalMigration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecipeManager.Api.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CookingDescription")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("FoodImage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(750);

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new { Id = new Guid("e28d1220-fd16-4f4b-b33b-494f108d8798"), CookingDescription = "tristique nulla aliquet enim tortor at auctor urna nunc id cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque", FoodImage = "", Title = "Mexican street salad" },
                        new { Id = new Guid("0d458067-0aa2-4fe3-96b2-18332ec0ace5"), CookingDescription = "nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui sapien eget mi proin sed libero enim sed faucibus turpis in eu mi bibendum", FoodImage = "", Title = "Mexican chicken tenders tray bake" },
                        new { Id = new Guid("9af1ef0a-2b38-47ca-9244-0de85bf28bf7"), CookingDescription = "a scelerisque purus semper eget duis at tellus at urna condimentum mattis pellentesque id nibh tortor id aliquet lectus proin nibh nisl condimentum id venenatis", FoodImage = "", Title = "Sweet and spicy chicken dippers with creamy dipping sauce" },
                        new { Id = new Guid("eeb31370-9b51-4990-9d50-ba9924ecb877"), CookingDescription = "eu ultrices vitae auctor eu augue ut lectus arcu bibendum at varius vel pharetra vel turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet", FoodImage = "", Title = "Mexican chicken with black bean salsa" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
